# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - Qr-Payment

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_bf0fd89d452341328a940a15013fe878 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_545b9cb64bd54feeb02189bdc4802a8d }}

    - run: |
        docker build . -t index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bf0fd89d452341328a940a15013fe878 }}/openjdk:${{ github.sha }}
        docker push index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bf0fd89d452341328a940a15013fe878 }}/openjdk:${{ github.sha }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Qr-Payment'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_25b67467b8434cd2a781ad5705674078 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_bf0fd89d452341328a940a15013fe878 }}/openjdk:${{ github.sha }}'